### ISSUE TITLE
External visuals

### ISSUE THREAD

**Issue by ahmetabdi** [LWSS/Ape-ex-Abominations#10]
💭 Thinking about adding some visuals (ESP) to this project but location data would have to be passed through to the VM as this is what does the displaying and the overlay would need to happen there in usermode by reading some data potentially? maybe JSON that constantly updating is while(true) loop? I'm not 100% sure on the best way to solve this have you had any thoughts @LWSS ?

I wanted to create this issue to brainstorms some ideas so I can get to implementing it.

**Comment by raspbianlike** [comment]
rendering client on windows
