### ISSUE TITLE
Initialization Error: 1

### ISSUE THREAD

**Issue by xNala** [LWSS/Ape-ex-Abominations#9]
Hello, I spent about half of today setting up GPU passthrough on the proxmox installation I had on my 2nd PC. I would say I have basic linux understanding and was able to compile your cheat and get to the point of being able to launch it without much trouble, except, when I do launch it, I get initialization error 1. Would you be able to provide me with more information on what this error is?
Please and thank you?

**Comment by LWSS** [comment]
https://github.com/Heep042/vmread/blob/master/pmparser.c#L80

this function fails so you're not running it as root or it can't find the qemu process

**Comment by xNala** [comment]
First of all, I would like to thank you for replying.

I am running as root, have tried with sudo as root too, not sure why that would help though.
https://pve.proxmox.com/wiki/Qemu-guest-agent
According to this, my VM and Host have QEMU running, doing the ping command with the VM ID works.
Which makes me think this is an issue with proxmox needing to specify a VM ID to be able to communicate with the QEMU guest.
Does vmread have to specify the VM ID to be able to communicate with the guest, or does it just go for the first running VM?

**Comment by LWSS** [comment]
looks like it just goes for the first one.

Issue is probably with proxmox, it's working with raw qemu and virt-manager, might be in some sort of container/sandbox, see if you can export the qemu args and just run it normally.

**Comment by xNala** [comment]
https://github.com/LWSS/Ape-ex-Abominations/blob/master/src/Main.cpp#L84
Error actually seems to be this line here.
On proxmox you need to specify the location of qemu
pidof /usr/bin/qemu-system-x86_64

Thank you for your help!
